theme: jekyll-theme-minimal
title: Koshakji
twitter_url: https://twitter.com/koshakji
instagram_url: https://instagram.com/koshakji
github_username: koshakji
description: 🤓
show_downloads: false
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Majd Koshakji"
