theme: jekyll-theme-minimal
title: Koshakji
description: Nothing to see here...yet!
show_downloads: false
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Majd Koshakji"
