baseURL = "https://koshakji.github.io"
languageCode = "en-us"
title = "Majd Koshakji"
theme =  ["github.com/Mitrichius/hugo-theme-anubis"]

[params]
author = "Majd Koshakji"
dateFormat = "2006-01-02"
style = "auto-without-switcher"
readMore = false
readNextPosts = 1
disableSummary = true
copyCodeButton = true
rssAsSocialIcon = true

[[params.social]]
id = "github"
name = "koshakji"

#[[params.social]]
#id = "twitter"
#name = "koshakji"
